/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.js.test.fir;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateJsTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/diagnostics/klibSerializationTests")
@TestDataPath("$PROJECT_ROOT")
public class FirPsiJsKlibDiagnosticsTestGenerated extends AbstractFirPsiJsDiagnosticWithBackendTest {
  @Test
  public void testAllFilesPresentInKlibSerializationTests() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
  }

  @Test
  @TestMetadata("signatureClashClasses.kt")
  public void testSignatureClashClasses() {
    runTest("compiler/testData/diagnostics/klibSerializationTests/signatureClashClasses.kt");
  }

  @Test
  @TestMetadata("signatureClashFunctions.kt")
  public void testSignatureClashFunctions() {
    runTest("compiler/testData/diagnostics/klibSerializationTests/signatureClashFunctions.kt");
  }

  @Test
  @TestMetadata("signatureClashVariables.kt")
  public void testSignatureClashVariables() {
    runTest("compiler/testData/diagnostics/klibSerializationTests/signatureClashVariables.kt");
  }

  @Test
  @TestMetadata("signatureClash_MPP.kt")
  public void testSignatureClash_MPP() {
    runTest("compiler/testData/diagnostics/klibSerializationTests/signatureClash_MPP.kt");
  }

  @Nested
  @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction")
  @TestDataPath("$PROJECT_ROOT")
  public class PrivateTypeUsageInsideNonPrivateInlineFunction {
    @Test
    public void testAllFilesPresentInPrivateTypeUsageInsideNonPrivateInlineFunction() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
    }

    @Test
    @TestMetadata("privateTypesInsideInternalInlineFunctionError.kt")
    public void testPrivateTypesInsideInternalInlineFunctionError() {
      runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/privateTypesInsideInternalInlineFunctionError.kt");
    }

    @Test
    @TestMetadata("privateTypesInsideInternalInlineFunctionWarning.kt")
    public void testPrivateTypesInsideInternalInlineFunctionWarning() {
      runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/privateTypesInsideInternalInlineFunctionWarning.kt");
    }

    @Nested
    @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors")
    @TestDataPath("$PROJECT_ROOT")
    public class SyntheticAccessors {
      @Test
      public void testAllFilesPresentInSyntheticAccessors() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
      }

      @Nested
      @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember")
      @TestDataPath("$PROJECT_ROOT")
      public class PrivateMember {
        @Test
        public void testAllFilesPresentInPrivateMember() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
        }

        @Nested
        @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossFilePrivateLeak")
        @TestDataPath("$PROJECT_ROOT")
        public class CrossFilePrivateLeak {
          @Test
          public void testAllFilesPresentInCrossFilePrivateLeak() {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossFilePrivateLeak"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
          }

          @Test
          @TestMetadata("leakingPrivateClassConstructor.kt")
          public void testLeakingPrivateClassConstructor() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossFilePrivateLeak/leakingPrivateClassConstructor.kt");
          }

          @Test
          @TestMetadata("usePrivateFunInterfaceFromInlineFun.kt")
          public void testUsePrivateFunInterfaceFromInlineFun() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossFilePrivateLeak/usePrivateFunInterfaceFromInlineFun.kt");
          }
        }

        @Nested
        @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossModulePrivateLeak")
        @TestDataPath("$PROJECT_ROOT")
        public class CrossModulePrivateLeak {
          @Test
          public void testAllFilesPresentInCrossModulePrivateLeak() {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossModulePrivateLeak"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
          }

          @Test
          @TestMetadata("leakingPrivateClassConstructor.kt")
          public void testLeakingPrivateClassConstructor() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossModulePrivateLeak/leakingPrivateClassConstructor.kt");
          }

          @Test
          @TestMetadata("usePrivateFunInterfaceFromInlineFun.kt")
          public void testUsePrivateFunInterfaceFromInlineFun() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/privateMember/crossModulePrivateLeak/usePrivateFunInterfaceFromInlineFun.kt");
          }
        }
      }

      @Nested
      @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate")
      @TestDataPath("$PROJECT_ROOT")
      public class TopLevelPrivate {
        @Test
        public void testAllFilesPresentInTopLevelPrivate() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
        }

        @Nested
        @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossFilePrivateLeak")
        @TestDataPath("$PROJECT_ROOT")
        public class CrossFilePrivateLeak {
          @Test
          public void testAllFilesPresentInCrossFilePrivateLeak() {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossFilePrivateLeak"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
          }

          @Test
          @TestMetadata("leakingPrivateClassThroughtKlass.kt")
          public void testLeakingPrivateClassThroughtKlass() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossFilePrivateLeak/leakingPrivateClassThroughtKlass.kt");
          }

          @Test
          @TestMetadata("leakingPrivateClassThroughtPrivateTopLevelFun.kt")
          public void testLeakingPrivateClassThroughtPrivateTopLevelFun() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossFilePrivateLeak/leakingPrivateClassThroughtPrivateTopLevelFun.kt");
          }

          @Test
          @TestMetadata("leakingPrivateClassThroughtTypecheck.kt")
          public void testLeakingPrivateClassThroughtTypecheck() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossFilePrivateLeak/leakingPrivateClassThroughtTypecheck.kt");
          }
        }

        @Nested
        @TestMetadata("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossModulePrivateLeak")
        @TestDataPath("$PROJECT_ROOT")
        public class CrossModulePrivateLeak {
          @Test
          public void testAllFilesPresentInCrossModulePrivateLeak() {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossModulePrivateLeak"), Pattern.compile("^([^_](.+))\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JS_IR, true);
          }

          @Test
          @TestMetadata("leakingPrivateClassThroughtKlass.kt")
          public void testLeakingPrivateClassThroughtKlass() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossModulePrivateLeak/leakingPrivateClassThroughtKlass.kt");
          }

          @Test
          @TestMetadata("leakingPrivateClassThroughtPrivateTopLevelFun.kt")
          public void testLeakingPrivateClassThroughtPrivateTopLevelFun() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossModulePrivateLeak/leakingPrivateClassThroughtPrivateTopLevelFun.kt");
          }

          @Test
          @TestMetadata("leakingPrivateClassThroughtTypecheck.kt")
          public void testLeakingPrivateClassThroughtTypecheck() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossModulePrivateLeak/leakingPrivateClassThroughtTypecheck.kt");
          }

          @Test
          @TestMetadata("potentiallyClashingPrivateClassAccessors.kt")
          public void testPotentiallyClashingPrivateClassAccessors() {
            runTest("compiler/testData/diagnostics/klibSerializationTests/privateTypeUsageInsideNonPrivateInlineFunction/syntheticAccessors/topLevelPrivate/crossModulePrivateLeak/potentiallyClashingPrivateClassAccessors.kt");
          }
        }
      }
    }
  }
}
